### ISSUE TITLE
ValueError: Surface level must be within volume data range.

### ISSUE THREAD

**Issue by 1309723614** [MoyGcc/vid2avatar#22]
Dear author, after the pre-processing of some video materials, errors will be reported in the training process. May I ask what might be the cause？
case1:
![image](https://github.com/MoyGcc/vid2avatar/assets/31795886/408b60d2-0850-4ea1-b567-1c7d2b30d47e)
case2:
![image](https://github.com/MoyGcc/vid2avatar/assets/31795886/2437a3ee-406d-480d-b3c7-dab1073d7eb1)

**Comment by MoyGcc** [comment]
Hi, this error is raised when the training fails to converge and the human shape network learns some random stuff instead of a proper human shape. Can you double-check the outputs of preprocessing and see whether the rendered SMPL aligns well with the human in the image space?

**Comment by 1309723614** [comment]
It has been solved. It is indeed a preprocessing problem. Thank you very much!!!

**Comment by areindaralnakhla** [comment]
how did you resolve this? i tried preprocessing the video again but it didn't seem to solve the issue..

**Comment by AreinDaralnakhla** [comment]
> It has been solved. It is indeed a preprocessing problem. Thank you very much!!!
